In [1]:
import numpy as np


In [2]:
print("NumPy version:", np.__version__)

np.show_config()

NumPy version: 2.1.3
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/alvas/anaconda3/Library/include
    lib directory: C:/Users/alvas/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_25aj347ekn\croot\numpy_and_numpy_base_1730835595898\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/alvas/anaconda3/Library/include
    lib directory: C:/Users/alvas/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_25aj347ekn\croot\numpy_and_numpy_base_1730835595898\_h_env\Library\lib\pkgconfig
    version: '2023.1'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30156
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30156
  cython:
    commands: cython
    linker: cytho

In [3]:
a = np.random.random((2, 3, 5))

In [6]:
print (a)

[[[0.05652156 0.72038546 0.54908194 0.7835943  0.30128941]
  [0.9288521  0.77829971 0.30037226 0.57455895 0.45591454]
  [0.24763384 0.92230717 0.83622236 0.83064687 0.34097221]]

 [[0.56261733 0.84694282 0.86305442 0.90414497 0.75006972]
  [0.13504569 0.40345086 0.30487524 0.6616755  0.56885306]
  [0.00778184 0.40087664 0.29053672 0.70303045 0.53025395]]]


In [7]:
b = np.ones((5, 2, 3))

In [9]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [10]:
print("Size of a:", a.size)
print("Size of b:", b.size)

print("Do a and b have the same size?", a.size == b.size)

Size of a: 30
Size of b: 30
Do a and b have the same size? True


In [11]:
print("Shape of a:", a.shape)
print("Shape of b:", b.shape)

try:
    c = a + b
    print("a and b can be added. Result shape:", c.shape)
except ValueError as e:
    print("a and b cannot be added. Reason:", e)

Shape of a: (2, 3, 5)
Shape of b: (5, 2, 3)
a and b cannot be added. Reason: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 


In [13]:
c = np.transpose(b, (1, 2, 0))

print("Shape of c:", c.shape)

Shape of c: (2, 3, 5)


In [14]:
d = a + c

print("Shape of d:", d.shape)
print("d =", d)

Shape of d: (2, 3, 5)
d = [[[1.05652156 1.72038546 1.54908194 1.7835943  1.30128941]
  [1.9288521  1.77829971 1.30037226 1.57455895 1.45591454]
  [1.24763384 1.92230717 1.83622236 1.83064687 1.34097221]]

 [[1.56261733 1.84694282 1.86305442 1.90414497 1.75006972]
  [1.13504569 1.40345086 1.30487524 1.6616755  1.56885306]
  [1.00778184 1.40087664 1.29053672 1.70303045 1.53025395]]]


In [15]:
print("Array a:")
print(a)

print("\nArray d (a + c):")
print(d)

Array a:
[[[0.05652156 0.72038546 0.54908194 0.7835943  0.30128941]
  [0.9288521  0.77829971 0.30037226 0.57455895 0.45591454]
  [0.24763384 0.92230717 0.83622236 0.83064687 0.34097221]]

 [[0.56261733 0.84694282 0.86305442 0.90414497 0.75006972]
  [0.13504569 0.40345086 0.30487524 0.6616755  0.56885306]
  [0.00778184 0.40087664 0.29053672 0.70303045 0.53025395]]]

Array d (a + c):
[[[1.05652156 1.72038546 1.54908194 1.7835943  1.30128941]
  [1.9288521  1.77829971 1.30037226 1.57455895 1.45591454]
  [1.24763384 1.92230717 1.83622236 1.83064687 1.34097221]]

 [[1.56261733 1.84694282 1.86305442 1.90414497 1.75006972]
  [1.13504569 1.40345086 1.30487524 1.6616755  1.56885306]
  [1.00778184 1.40087664 1.29053672 1.70303045 1.53025395]]]


In [16]:
e = a * c

print("Shape of e:", e.shape)
print("e =", e)


Shape of e: (2, 3, 5)
e = [[[0.05652156 0.72038546 0.54908194 0.7835943  0.30128941]
  [0.9288521  0.77829971 0.30037226 0.57455895 0.45591454]
  [0.24763384 0.92230717 0.83622236 0.83064687 0.34097221]]

 [[0.56261733 0.84694282 0.86305442 0.90414497 0.75006972]
  [0.13504569 0.40345086 0.30487524 0.6616755  0.56885306]
  [0.00778184 0.40087664 0.29053672 0.70303045 0.53025395]]]


In [17]:
print("Does e equal a?", np.array_equal(e, a))

Does e equal a? True


In [18]:
d_max = np.max(d)

d_min = np.min(d)

d_mean = np.mean(d)

print("d_max =", d_max)
print("d_min =", d_min)
print("d_mean =", d_mean)

d_max = 1.9288520989287345
d_min = 1.0077818363185924
d_mean = 1.5519953966522906


In [20]:
f = np.empty(d.shape)

print("Shape of f:", f.shape)

Shape of f: (2, 3, 5)


In [21]:
shape = d.shape

for i in range(shape[0]):
    for j in range(shape[1]):
        for k in range(shape[2]):
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75

print("Labeled array f:")
print(f)

Labeled array f:
[[[ 25.  75.  25.  75.  25.]
  [100.  75.  25.  75.  25.]
  [ 25.  75.  75.  75.  25.]]

 [[ 75.  75.  75.  75.  75.]
  [ 25.  25.  25.  75.  75.]
  [  0.  25.  25.  75.  25.]]]


In [22]:
print("Array d:")
print(d)

print("\nLabeled array f:")
print(f)

Array d:
[[[1.05652156 1.72038546 1.54908194 1.7835943  1.30128941]
  [1.9288521  1.77829971 1.30037226 1.57455895 1.45591454]
  [1.24763384 1.92230717 1.83622236 1.83064687 1.34097221]]

 [[1.56261733 1.84694282 1.86305442 1.90414497 1.75006972]
  [1.13504569 1.40345086 1.30487524 1.6616755  1.56885306]
  [1.00778184 1.40087664 1.29053672 1.70303045 1.53025395]]]

Labeled array f:
[[[ 25.  75.  25.  75.  25.]
  [100.  75.  25.  75.  25.]
  [ 25.  75.  75.  75.  25.]]

 [[ 75.  75.  75.  75.  75.]
  [ 25.  25.  25.  75.  75.]
  [  0.  25.  25.  75.  25.]]]


In [23]:
f_str = np.empty(d.shape, dtype=object)

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f_str[i, j, k] = "A"
            elif d[i, j, k] == d_max:
                f_str[i, j, k] = "E"
            elif d[i, j, k] == d_mean:
                f_str[i, j, k] = "C"
            elif d_min < d[i, j, k] < d_mean:
                f_str[i, j, k] = "B"
            elif d_mean < d[i, j, k] < d_max:
                f_str[i, j, k] = "D"

print("Labeled array with strings:")
print(f_str)

Labeled array with strings:
[[['B' 'D' 'B' 'D' 'B']
  ['E' 'D' 'B' 'D' 'B']
  ['B' 'D' 'D' 'D' 'B']]

 [['D' 'D' 'D' 'D' 'D']
  ['B' 'B' 'B' 'D' 'D']
  ['A' 'B' 'B' 'D' 'B']]]
